// プログラミング用語データベース
// tier: basic(初級) / intermediate(中級) / advanced(上級)
// unit : 言語ごとの単元キー（UNITSで定義）

const WORDS = {
  python: [
    // 基礎（print・変数・簡単な計算・簡単な条件分岐・簡単な繰り返しのみに絞る）
    { term: "print()", def: "画面に表示する命令", tier: "basic", unit: "basic" },
    { term: "変数", def: "値を入れる箱", tier: "basic", unit: "basic" },
    { term: "算術演算子 (+ - * /)", def: "数値を計算する記号", tier: "basic", unit: "basic" },
    { term: "input()", def: "入力を受け取る関数", tier: "basic", unit: "basic" },
    { term: "len()", def: "長さを調べる関数", tier: "basic", unit: "basic" },
    { term: "コメント (#)", def: "実行されない説明書き", tier: "basic", unit: "basic" },
    { term: "str()", def: "文字列に変換する関数", tier: "basic", unit: "basic" },
    { term: "if", def: "条件で処理を分岐する", tier: "basic", unit: "basic" },
    { term: "elif", def: "次の条件を確認する", tier: "basic", unit: "basic" },
    { term: "else", def: "当てはまらない時の処理", tier: "basic", unit: "basic" },
    { term: "比較演算子 (== !=)", def: "値を比較する記号", tier: "basic", unit: "basic" },
    { term: "for", def: "決まった回数繰り返す", tier: "basic", unit: "basic" },
    { term: "range()", def: "数値の範囲を作る関数", tier: "basic", unit: "basic" },

    // 関数
    { term: "def", def: "関数を定義する命令", tier: "basic", unit: "func" },
    { term: "return", def: "処理結果を返す命令", tier: "basic", unit: "func" },
    { term: "引数", def: "関数に渡す値", tier: "basic", unit: "func" },
    { term: "戻り値", def: "関数が返す値", tier: "basic", unit: "func" },
    { term: "関数呼び出し", def: "関数を実行すること", tier: "basic", unit: "func" },
    { term: "位置引数", def: "順番通りに渡す引数", tier: "intermediate", unit: "func" },
    { term: "キーワード引数", def: "引数名を指定して渡す", tier: "intermediate", unit: "func" },
    { term: "デフォルト引数", def: "省略時に使う初期値", tier: "intermediate", unit: "func" },
    { term: "可変長引数", def: "個数が決まらない引数", tier: "intermediate", unit: "func" },
    { term: "docstring", def: "関数の説明を書く文字列", tier: "intermediate", unit: "func" },
    { term: "スコープ", def: "変数の有効範囲", tier: "intermediate", unit: "func" },
    { term: "lambda", def: "名前のない小さな関数", tier: "advanced", unit: "func" },
    { term: "*args / **kwargs", def: "任意の数の引数を渡す書き方", tier: "advanced", unit: "func" },
    { term: "再帰関数", def: "自分自身を呼び出す関数", tier: "advanced", unit: "func" },
    { term: "純粋関数", def: "副作用のない関数", tier: "advanced", unit: "func" },
    { term: "高階関数", def: "関数を引数や戻り値にする", tier: "advanced", unit: "func" },
    { term: "メモ化", def: "結果を保存し再利用する", tier: "advanced", unit: "func" },
    { term: "部分適用", def: "引数の一部を固定した関数", tier: "advanced", unit: "func" },
    { term: "関数アノテーション", def: "型を注釈する書き方", tier: "advanced", unit: "func" },
    { term: "即時関数", def: "定義後すぐ呼び出す関数", tier: "advanced", unit: "func" },

    // 中級（型・文字列操作・論理演算子・応用的な繰り返し＋データ構造）
    { term: "type()", def: "型を調べる関数", tier: "intermediate", unit: "data" },
    { term: "f文字列 (f\"...\")", def: "変数を埋め込む文字列", tier: "intermediate", unit: "data" },
    { term: "and", def: "両方が真か判定する", tier: "intermediate", unit: "data" },
    { term: "or", def: "どちらかが真か判定する", tier: "intermediate", unit: "data" },
    { term: "not", def: "真偽を反転させる", tier: "intermediate", unit: "data" },
    { term: "in", def: "含まれるか調べる", tier: "intermediate", unit: "data" },
    { term: "while", def: "条件が真の間繰り返す", tier: "basic", unit: "data" },
    { term: "break", def: "ループを途中で終了する", tier: "basic", unit: "data" },
    { term: "continue", def: "今回だけ飛ばして次へ進む", tier: "basic", unit: "data" },
    { term: "enumerate()", def: "要素と番号を同時に取得", tier: "intermediate", unit: "data" },
    { term: "while True", def: "無限に繰り返す書き方", tier: "intermediate", unit: "data" },
    { term: "リスト (list)", def: "値を順番に並べる構造", tier: "intermediate", unit: "data" },
    { term: "辞書 (dict)", def: "キーと値で管理する構造", tier: "intermediate", unit: "data" },
    { term: "タプル (tuple)", def: "変更できない順序付き構造", tier: "intermediate", unit: "data" },
    { term: "セット (set)", def: "重複を許さない集まり", tier: "intermediate", unit: "data" },
    { term: "スライス ([:])", def: "一部分を取り出す書き方", tier: "intermediate", unit: "data" },
    { term: "インデックス", def: "要素の位置番号", tier: "basic", unit: "data" },
    { term: "append()", def: "末尾に要素を追加する", tier: "intermediate", unit: "data" },
    { term: "pop()", def: "取り出して削除するメソッド", tier: "intermediate", unit: "data" },
    { term: "remove()", def: "値を指定して削除する", tier: "intermediate", unit: "data" },
    { term: "insert()", def: "指定位置に要素を挿入する", tier: "intermediate", unit: "data" },
    { term: "sort()", def: "中身を並べ替える", tier: "intermediate", unit: "data" },
    { term: "reverse()", def: "順序を逆にするメソッド", tier: "intermediate", unit: "data" },
    { term: "count()", def: "出現回数を数えるメソッド", tier: "intermediate", unit: "data" },
    { term: "keys()", def: "辞書のキー一覧を取得する", tier: "intermediate", unit: "data" },
    { term: "values()", def: "辞書の値一覧を取得する", tier: "intermediate", unit: "data" },
    { term: "items()", def: "キーと値の組を取得する", tier: "intermediate", unit: "data" },
    { term: "get()", def: "安全に値を取得するメソッド", tier: "intermediate", unit: "data" },
    { term: "join()", def: "文字列をつなげるメソッド", tier: "intermediate", unit: "data" },
    { term: "リスト内包表記", def: "1行で書けるリスト作成", tier: "advanced", unit: "data" },
    { term: "辞書内包表記", def: "短く書ける辞書作成", tier: "advanced", unit: "data" },

    // クラス
    { term: "class", def: "オブジェクトの設計図", tier: "intermediate", unit: "oop" },
    { term: "self", def: "自分自身を指す変数", tier: "intermediate", unit: "oop" },
    { term: "__init__", def: "作成時に呼ばれる初期化", tier: "intermediate", unit: "oop" },
    { term: "インスタンス", def: "クラスから作った実体", tier: "intermediate", unit: "oop" },
    { term: "メソッド", def: "クラス内の関数", tier: "intermediate", unit: "oop" },
    { term: "クラス変数", def: "クラス全体で共有する変数", tier: "intermediate", unit: "oop" },
    { term: "インスタンス変数", def: "インスタンスごとに持つ変数", tier: "intermediate", unit: "oop" },
    { term: "super()", def: "親クラスの機能を呼び出す", tier: "intermediate", unit: "oop" },
    { term: "継承 (inheritance)", def: "機能を引き継ぐ仕組み", tier: "advanced", unit: "oop" },
    { term: "オーバーライド", def: "親のメソッドを上書きする", tier: "advanced", unit: "oop" },
    { term: "ポリモーフィズム", def: "同名メソッドで違う動作", tier: "advanced", unit: "oop" },
    { term: "カプセル化", def: "内部にまとめて隠す考え方", tier: "advanced", unit: "oop" },
    { term: "抽象クラス", def: "そのままでは使えないクラス", tier: "advanced", unit: "oop" },
    { term: "マジックメソッド", def: "__で囲まれた特殊メソッド", tier: "advanced", unit: "oop" },
    { term: "__str__", def: "文字列表現を返すメソッド", tier: "advanced", unit: "oop" },
    { term: "プロパティ", def: "属性のように扱うメソッド", tier: "advanced", unit: "oop" },
    { term: "多重継承", def: "複数のクラスから継承する", tier: "advanced", unit: "oop" },
    { term: "staticmethod", def: "インスタンスなしで呼べる", tier: "advanced", unit: "oop" },
    { term: "classmethod", def: "クラス自体を引数に取る", tier: "advanced", unit: "oop" },
    { term: "ダックタイピング", def: "振る舞いを重視する考え方", tier: "advanced", unit: "oop" },

    // 例外処理
    { term: "try / except", def: "エラーに対応する構文", tier: "intermediate", unit: "error" },
    { term: "except", def: "エラーを受け取り処理する節", tier: "intermediate", unit: "error" },
    { term: "複数except", def: "複数の種類のエラーに対応", tier: "intermediate", unit: "error" },
    { term: "finally", def: "最後に必ず実行される処理", tier: "advanced", unit: "error" },
    { term: "raise", def: "意図的にエラーを出す命令", tier: "advanced", unit: "error" },
    { term: "例外クラス", def: "エラーの種類を表すクラス", tier: "advanced", unit: "error" },
    { term: "Exception", def: "すべての例外の基本クラス", tier: "intermediate", unit: "error" },
    { term: "ValueError", def: "値が不正なときのエラー", tier: "intermediate", unit: "error" },
    { term: "TypeError", def: "型が違うときのエラー", tier: "intermediate", unit: "error" },
    { term: "KeyError", def: "存在しないキーのエラー", tier: "intermediate", unit: "error" },
    { term: "IndexError", def: "範囲外を指定したエラー", tier: "intermediate", unit: "error" },
    { term: "assert", def: "条件を確認しエラーを出す", tier: "advanced", unit: "error" },
    { term: "with文", def: "リソースを安全に扱う構文", tier: "advanced", unit: "error" },
    { term: "__enter__/__exit__", def: "withで使う特殊メソッド", tier: "advanced", unit: "error" },
    { term: "トレースバック", def: "エラー発生箇所を示す記録", tier: "advanced", unit: "error" },
    { term: "スタックトレース", def: "関数呼び出しの履歴", tier: "advanced", unit: "error" },
    { term: "カスタム例外", def: "自分で定義するエラー", tier: "advanced", unit: "error" },
    { term: "例外の再送出", def: "エラーを再び発生させる", tier: "advanced", unit: "error" },
    { term: "デバッグ", def: "不具合を探して直す作業", tier: "basic", unit: "error" },
    { term: "ロギング", def: "実行記録を残す仕組み", tier: "advanced", unit: "error" },

    // 応用
    { term: "ネストしたループ", def: "ループの中の別のループ", tier: "advanced", unit: "advanced" },
    { term: "デコレータ (@)", def: "関数に処理を追加する仕組み", tier: "advanced", unit: "advanced" },
    { term: "yield", def: "値を返しつつ一時停止する", tier: "advanced", unit: "advanced" },
    { term: "ジェネレータ", def: "値を1つずつ返す関数", tier: "advanced", unit: "advanced" },
    { term: "ジェネレータ式", def: "短く書けるジェネレータ", tier: "advanced", unit: "advanced" },
    { term: "イテレータ", def: "順番に値を取り出す仕組み", tier: "advanced", unit: "advanced" },
    { term: "イテラブル", def: "for文で繰り返せるもの", tier: "advanced", unit: "advanced" },
    { term: "モジュール (import)", def: "他ファイルの機能を読込む", tier: "intermediate", unit: "advanced" },
    { term: "パッケージ", def: "モジュールをまとめたもの", tier: "intermediate", unit: "advanced" },
    { term: "標準ライブラリ", def: "最初から入っている機能", tier: "intermediate", unit: "advanced" },
    { term: "pip", def: "パッケージを管理するツール", tier: "intermediate", unit: "advanced" },
    { term: "コンテキストマネージャ", def: "withで使うリソース管理", tier: "advanced", unit: "advanced" },
    { term: "__name__ == \"__main__\"", def: "直接実行時だけ動く書き方", tier: "advanced", unit: "advanced" },
    { term: "型ヒント", def: "型を注釈として書く方法", tier: "advanced", unit: "advanced" },
    { term: "仮想環境 (venv)", def: "パッケージを分離する環境", tier: "advanced", unit: "advanced" },
    { term: "マルチスレッド", def: "処理を並行して行う仕組み", tier: "advanced", unit: "advanced" },
    { term: "マルチプロセス", def: "プロセス単位の並行処理", tier: "advanced", unit: "advanced" },
    { term: "GIL", def: "排他制御の仕組み", tier: "advanced", unit: "advanced" },
    { term: "メタクラス", def: "クラスを作るクラス", tier: "advanced", unit: "advanced" },
    { term: "モンキーパッチ", def: "実行中にコードを書き換える", tier: "advanced", unit: "advanced" },
    { term: "PEP8", def: "コーディング規約", tier: "intermediate", unit: "advanced" },
  ],
  html: [
    { term: "&lt;div&gt;", def: "要素をまとめる箱タグ", tier: "basic", unit: "tag_basic" },
    { term: "&lt;p&gt;", def: "段落を表すタグ", tier: "basic", unit: "heading_text" },
    { term: "&lt;a&gt;", def: "リンクを作るタグ", tier: "basic", unit: "link_media" },
    { term: "&lt;img&gt;", def: "画像を表示するタグ", tier: "basic", unit: "link_media" },
    { term: "&lt;h1&gt;", def: "最も重要な見出しタグ", tier: "basic", unit: "heading_text" },
    { term: "&lt;ul&gt; / &lt;li&gt;", def: "箇条書きリストのタグ", tier: "basic", unit: "list_table" },
    { term: "&lt;form&gt;", def: "入力を送信するフォーム", tier: "intermediate", unit: "form" },
    { term: "&lt;input&gt;", def: "入力欄を作るタグ", tier: "intermediate", unit: "form" },
    { term: "&lt;table&gt;", def: "表を作るタグ", tier: "intermediate", unit: "list_table" },
    { term: "class属性", def: "複数要素に付けられる名前", tier: "intermediate", unit: "attr" },
    { term: "id属性", def: "1つだけの要素を識別する名前", tier: "intermediate", unit: "attr" },
    { term: "&lt;span&gt;", def: "文章の一部を装飾するタグ", tier: "intermediate", unit: "tag_basic" },
    { term: "&lt;section&gt;", def: "意味のあるまとまりのタグ", tier: "advanced", unit: "semantic" },
    { term: "&lt;article&gt;", def: "独立した記事を表すタグ", tier: "advanced", unit: "semantic" },
    { term: "data-*属性", def: "独自のデータを持たせる属性", tier: "advanced", unit: "data_a11y" },
    { term: "&lt;canvas&gt;", def: "図形や画像を描画するタグ", tier: "advanced", unit: "semantic" },
    { term: "&lt;template&gt;", def: "複製して使うひな形タグ", tier: "advanced", unit: "semantic" },
    { term: "ARIA属性", def: "支援技術に情報を伝える属性", tier: "advanced", unit: "data_a11y" },
  ],
  css: [
    { term: "color", def: "文字の色を指定する", tier: "basic", unit: "text" },
    { term: "background-color", def: "背景色を指定する", tier: "basic", unit: "background" },
    { term: "font-size", def: "文字の大きさを指定する", tier: "basic", unit: "text" },
    { term: "margin", def: "外側の余白を指定する", tier: "basic", unit: "box" },
    { term: "padding", def: "内側の余白を指定する", tier: "basic", unit: "box" },
    { term: "border", def: "要素に枠線を付ける", tier: "basic", unit: "box" },
    { term: "クラスセレクタ (.)", def: "同じclass名の要素に適用", tier: "intermediate", unit: "selector" },
    { term: "IDセレクタ (#)", def: "特定のid名の要素に適用", tier: "intermediate", unit: "selector" },
    { term: "display: flex", def: "要素を横並びに整列する", tier: "intermediate", unit: "layout" },
    { term: "position", def: "要素の配置方法を指定する", tier: "intermediate", unit: "position" },
    { term: ":hover", def: "マウスが乗った時のスタイル", tier: "intermediate", unit: "selector" },
    { term: "メディアクエリ", def: "画面幅で切り替える仕組み", tier: "intermediate", unit: "responsive" },
    { term: "display: grid", def: "行と列でレイアウトを組む", tier: "advanced", unit: "layout" },
    { term: "z-index", def: "要素の重なり順を指定する", tier: "advanced", unit: "position" },
    { term: "transform", def: "要素を回転・拡大させる", tier: "advanced", unit: "animation" },
    { term: "transition", def: "変化を滑らかにする", tier: "advanced", unit: "animation" },
    { term: "@keyframes", def: "アニメーションの動きを定義", tier: "advanced", unit: "animation" },
    { term: "calc()", def: "値を計算して指定する関数", tier: "advanced", unit: "responsive" },
  ],
  javascript: [
    { term: "console.log()", def: "コンソールに値を表示する", tier: "basic", unit: "output_var" },
    { term: "let / const", def: "変数を宣言するキーワード", tier: "basic", unit: "output_var" },
    { term: "function", def: "関数を定義するキーワード", tier: "basic", unit: "func_basic" },
    { term: "if文", def: "条件で処理を分岐する", tier: "basic", unit: "control" },
    { term: "for文", def: "処理を繰り返す構文", tier: "basic", unit: "control" },
    { term: "配列 (Array)", def: "値を順番に格納する構造", tier: "basic", unit: "data" },
    { term: "addEventListener", def: "イベント発生時の処理を登録", tier: "intermediate", unit: "dom" },
    { term: "アロー関数 (=&gt;)", def: "短く関数を定義する記法", tier: "intermediate", unit: "func_style" },
    { term: "JSON", def: "データをやり取りする形式", tier: "intermediate", unit: "data" },
    { term: "map()", def: "加工した新しい配列を作る", tier: "intermediate", unit: "func_style" },
    { term: "DOM", def: "HTML文書を操作する仕組み", tier: "intermediate", unit: "dom" },
    { term: "this", def: "呼び出し元の文脈を指す", tier: "intermediate", unit: "func_style" },
    { term: "Promise", def: "非同期処理の結果を扱う", tier: "advanced", unit: "async" },
    { term: "async / await", def: "非同期処理を同期的に書く", tier: "advanced", unit: "async" },
    { term: "クロージャ", def: "スコープの変数を覚え続ける", tier: "advanced", unit: "scope" },
    { term: "プロトタイプ", def: "機能を共有する仕組み", tier: "advanced", unit: "scope" },
    { term: "スプレッド構文 (...)", def: "中身を展開してコピーする", tier: "advanced", unit: "scope" },
    { term: "コールバック関数", def: "後で呼び出される関数", tier: "advanced", unit: "func_style" },
  ],
};

const LANG_LABELS = {
  python: "Python",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
};

const LANG_ICON = { python: "🐍", html: "🌐", css: "🎨", javascript: "⚡" };

// 言語ごとの単元一覧（表示順）
const UNITS = {
  python: [
    { key: "basic", label: "基礎" },
    { key: "func", label: "関数" },
    { key: "data", label: "中級" },
    { key: "oop", label: "クラス" },
    { key: "error", label: "例外処理" },
    { key: "advanced", label: "応用" },
  ],
  html: [
    { key: "tag_basic", label: "構造タグ" },
    { key: "heading_text", label: "見出し・段落" },
    { key: "link_media", label: "リンク・画像" },
    { key: "list_table", label: "リスト・表" },
    { key: "form", label: "フォーム" },
    { key: "attr", label: "属性" },
    { key: "data_a11y", label: "データ・アクセシビリティ" },
    { key: "semantic", label: "セマンティック・応用" },
  ],
  css: [
    { key: "text", label: "文字" },
    { key: "background", label: "背景" },
    { key: "box", label: "余白・枠線" },
    { key: "selector", label: "セレクタ・状態" },
    { key: "layout", label: "フレックス・グリッド" },
    { key: "position", label: "配置" },
    { key: "animation", label: "アニメーション" },
    { key: "responsive", label: "レスポンシブ・計算" },
  ],
  javascript: [
    { key: "output_var", label: "出力・変数" },
    { key: "func_basic", label: "関数の基本" },
    { key: "control", label: "制御構文" },
    { key: "data", label: "配列・データ" },
    { key: "dom", label: "DOM・イベント" },
    { key: "func_style", label: "関数の書き方" },
    { key: "async", label: "非同期処理" },
    { key: "scope", label: "スコープ・応用" },
  ],
};
