// 並べ替え問題データベース
// tokens: 正しい順番でコードを構成する単語・フレーズの配列
// unit  : js/data.js の UNITS で定義された単元キーと対応

const ORDER_PROBLEMS = {
  python: [
    // 基礎：出力・変数・簡単な計算
    { prompt: "変数 x に 10 を代入するコードに並べ替えてください", tokens: ["x", "=", "10"], unit: "basic" },
    { prompt: "「Hello」と表示するコードに並べ替えてください", tokens: ["print(", "\"Hello\"", ")"], unit: "basic" },
    { prompt: "変数nameに「Taro」を代入するコードに並べ替えてください", tokens: ["name", "=", "\"Taro\""], unit: "basic" },
    { prompt: "input()でユーザーの入力を受け取るコードに並べ替えてください", tokens: ["name", "=", "input()"], unit: "basic" },
    { prompt: "変数ageに20を代入するコードに並べ替えてください", tokens: ["age", "=", "20"], unit: "basic" },
    { prompt: "10と3を足した結果を表示するコードに並べ替えてください", tokens: ["print(", "10 + 3", ")"], unit: "basic" },
    { prompt: "変数xとyを足して表示するコードに並べ替えてください", tokens: ["print(", "x + y", ")"], unit: "basic" },
    { prompt: "「Hello」と「World」をつなげて表示するコードに並べ替えてください", tokens: ["print(", "\"Hello\" + \"World\"", ")"], unit: "basic" },
    // 基礎：簡単な条件分岐
    { prompt: "xが1なら「Yes」と表示するコードに並べ替えてください", tokens: ["if", "x == 1:", "print(\"Yes\")"], unit: "basic" },
    { prompt: "xが10より大きいなら「Big」と表示するコードに並べ替えてください", tokens: ["if", "x > 10:", "print(\"Big\")"], unit: "basic" },
    { prompt: "xが1でなければ「No」と表示するコードに並べ替えてください", tokens: ["if", "x != 1:", "print(\"No\")"], unit: "basic" },
    { prompt: "xが1なら「A」、そうでなければ「B」と表示するコードに並べ替えてください", tokens: ["if", "x == 1:", "print(\"A\")", "else:", "print(\"B\")"], unit: "basic" },
    { prompt: "xが5以上か調べるコードに並べ替えてください", tokens: ["if", "x >= 5:", "print(\"OK\")"], unit: "basic" },
    // 基礎：for i in range() の簡単な繰り返しと組み込み関数
    { prompt: "1から5まで出力するfor文に並べ替えてください", tokens: ["for", "i in range(1, 6):", "print(i)"], unit: "basic" },
    { prompt: "xの長さを表示するコードに並べ替えてください", tokens: ["print(", "len(x)", ")"], unit: "basic" },
    // 関数：まずは簡単な関数を定義して使うレベルにとどめる
    { prompt: "関数greetを定義して「Hello」を返すコードに並べ替えてください", tokens: ["def", "greet():", "return \"Hello\""], unit: "func" },
    { prompt: "2つの数を足す関数addを定義するコードに並べ替えてください", tokens: ["def", "add(a, b):", "return a + b"], unit: "func" },
    { prompt: "数を2乗して返す関数に並べ替えてください", tokens: ["def", "square(x):", "return x * x"], unit: "func" },
    { prompt: "3つの数の最大値を返す関数に並べ替えてください", tokens: ["def", "max3(a, b, c):", "return max(a, b, c)"], unit: "func" },
    { prompt: "税込み価格を計算する純粋関数に並べ替えてください", tokens: ["def", "with_tax(price):", "return price * 1.1"], unit: "func" },
    { prompt: "2つの数をかけ算する関数multiplyを定義するコードに並べ替えてください", tokens: ["def", "multiply(a, b):", "return a * b"], unit: "func" },
    { prompt: "名前を表示するだけの関数say_helloを定義するコードに並べ替えてください", tokens: ["def", "say_hello():", "print(\"Hello!\")"], unit: "func" },
    { prompt: "数を受け取って2倍にして返す関数doubleを定義するコードに並べ替えてください", tokens: ["def", "double(n):", "return n * 2"], unit: "func" },
    { prompt: "2つの数を引き算する関数subtractを定義するコードに並べ替えてください", tokens: ["def", "subtract(a, b):", "return a - b"], unit: "func" },
    // 中級：型・文字列操作・論理演算子
    { prompt: "変数xの型を調べて表示するコードに並べ替えてください", tokens: ["print(", "type(x)", ")"], unit: "data" },
    { prompt: "f文字列で挨拶を表示するコードに並べ替えてください", tokens: ["print(", "f\"Hello, {name}\"", ")"], unit: "data" },
    { prompt: "リストに3が含まれるか調べるコードに並べ替えてください", tokens: ["if", "3 in numbers:", "print(\"Found\")"], unit: "data" },
    { prompt: "xが0より大きく10未満か調べるコードに並べ替えてください", tokens: ["if", "x > 0 and x < 10:", "print(\"OK\")"], unit: "data" },
    // 中級：応用的な繰り返し（while・break・複合for）
    { prompt: "リストfruitsの中身を順番に表示するコードに並べ替えてください", tokens: ["for", "fruit in fruits:", "print(fruit)"], unit: "data" },
    { prompt: "xが10未満の間繰り返すコードに並べ替えてください", tokens: ["while", "x < 10:", "x += 1"], unit: "data" },
    { prompt: "5になったらループを止めるコードに並べ替えてください", tokens: ["for", "i in range(10):", "if i == 5:", "break"], unit: "data" },
    { prompt: "偶数だけを表示するコードに並べ替えてください", tokens: ["for", "n in numbers:", "if n % 2 == 0:", "print(n)"], unit: "data" },
    { prompt: "無限に繰り返すコードに並べ替えてください", tokens: ["while", "True:", "print(\"loop\")"], unit: "data" },
    // 中級：関数から移動した、やや発展的な引数の使い方
    { prompt: "デフォルト引数を持つ関数を定義するコードに並べ替えてください", tokens: ["def", "greet(name=\"guest\"):", "print(name)"], unit: "data" },
    { prompt: "キーワード引数を指定して関数を呼び出すコードに並べ替えてください", tokens: ["greet(", "name=\"Taro\"", ")"], unit: "data" },
    { prompt: "docstringを持つ関数を定義するコードに並べ替えてください", tokens: ["def", "greet():", "\"\"\"挨拶を表示する\"\"\"", "print(\"Hi\")"], unit: "data" },
    { prompt: "デフォルト引数で計算方法を固定する関数に並べ替えてください", tokens: ["def", "power(base, exp=2):", "return base ** exp"], unit: "data" },
    { prompt: "色を指定して関数を呼び出すコードに並べ替えてください", tokens: ["paint(", "color=\"red\"", ")"], unit: "data" },
    // データ構造
    { prompt: "リストnumbersを作成するコードに並べ替えてください", tokens: ["numbers", "=", "[1, 2, 3]"], unit: "data" },
    { prompt: "辞書personを作成するコードに並べ替えてください", tokens: ["person", "=", "{\"name\": \"Taro\"}"], unit: "data" },
    { prompt: "タプルpointを作成するコードに並べ替えてください", tokens: ["point", "=", "(1, 2)"], unit: "data" },
    { prompt: "セットを作成するコードに並べ替えてください", tokens: ["numbers", "=", "{1, 2, 3}"], unit: "data" },
    { prompt: "リストの先頭2つを取り出すスライスに並べ替えてください", tokens: ["first_two", "=", "numbers[0:2]"], unit: "data" },
    { prompt: "リストの末尾に要素を追加するコードに並べ替えてください", tokens: ["numbers.append(", "4", ")"], unit: "data" },
    { prompt: "リストの最後の要素を取り出して削除するコードに並べ替えてください", tokens: ["last", "=", "numbers.pop()"], unit: "data" },
    { prompt: "指定した値をリストから削除するコードに並べ替えてください", tokens: ["numbers.remove(", "3", ")"], unit: "data" },
    { prompt: "リストの先頭に要素を挿入するコードに並べ替えてください", tokens: ["numbers.insert(", "0,", "1", ")"], unit: "data" },
    { prompt: "リストを降順に並べ替えるコードに並べ替えてください", tokens: ["numbers.sort(", "reverse=True", ")"], unit: "data" },
    { prompt: "スライスでリストを反転させるコードに並べ替えてください", tokens: ["numbers", "=", "numbers[::-1]"], unit: "data" },
    { prompt: "リスト内の要素の出現回数を数えるコードに並べ替えてください", tokens: ["numbers.count(", "2", ")"], unit: "data" },
    { prompt: "辞書のキー一覧を取得するコードに並べ替えてください", tokens: ["names", "=", "person.keys()"], unit: "data" },
    { prompt: "辞書の値一覧を取得するコードに並べ替えてください", tokens: ["values", "=", "person.values()"], unit: "data" },
    { prompt: "辞書のキーと値をまとめて取り出すコードに並べ替えてください", tokens: ["for", "k, v in person.items():", "print(k, v)"], unit: "data" },
    { prompt: "辞書から安全に値を取得するコードに並べ替えてください", tokens: ["age", "=", "person.get(\"age\", 0)"], unit: "data" },
    { prompt: "リストの要素を文字列でつなげるコードに並べ替えてください", tokens: ["text", "=", "\", \".join(names)"], unit: "data" },
    { prompt: "偶数だけのリストを内包表記で作るコードに並べ替えてください", tokens: ["evens", "=", "[n for n in numbers if n % 2 == 0]"], unit: "data" },
    { prompt: "辞書内包表記で値を2倍にするコードに並べ替えてください", tokens: ["doubled", "=", "{k: v * 2 for k, v in person.items()}"], unit: "data" },
    { prompt: "リストの3番目の要素をインデックスで取得するコードに並べ替えてください", tokens: ["third", "=", "numbers[2]"], unit: "data" },
    // クラス
    { prompt: "クラスDogを定義するコードに並べ替えてください", tokens: ["class", "Dog:", "def bark(self):", "print(\"Woof\")"], unit: "oop" },
    { prompt: "クラスCarに初期化メソッドを追加するコードに並べ替えてください", tokens: ["class", "Car:", "def __init__(self):", "self.speed = 0"], unit: "oop" },
    { prompt: "クラスAnimalを継承するクラスCatを定義するコードに並べ替えてください", tokens: ["class", "Cat(Animal):", "pass"], unit: "oop" },
    { prompt: "コンストラクタで名前を設定するコードに並べ替えてください", tokens: ["def", "__init__(self, name):", "self.name = name"], unit: "oop" },
    { prompt: "クラスDogからインスタンスを作成するコードに並べ替えてください", tokens: ["dog", "=", "Dog()"], unit: "oop" },
    { prompt: "self.nameを表示するメソッドを定義するコードに並べ替えてください", tokens: ["def", "introduce(self):", "print(self.name)"], unit: "oop" },
    { prompt: "クラス全体で共有するクラス変数に並べ替えてください", tokens: ["class", "Dog:", "species = \"Canine\""], unit: "oop" },
    { prompt: "年齢を初期化するコンストラクタに並べ替えてください", tokens: ["def", "__init__(self, age):", "self.age = age"], unit: "oop" },
    { prompt: "親クラスの初期化を呼び出すコードに並べ替えてください", tokens: ["class", "Cat(Animal):", "def __init__(self):", "super().__init__()"], unit: "oop" },
    { prompt: "親クラスのメソッドを上書きするコードに並べ替えてください", tokens: ["class", "Cat(Animal):", "def speak(self):", "print(\"Meow\")"], unit: "oop" },
    { prompt: "そのままでは使えない抽象クラスに並べ替えてください", tokens: ["class", "Shape:", "def area(self):", "raise NotImplementedError"], unit: "oop" },
    { prompt: "オブジェクトを文字列として表示するマジックメソッドに並べ替えてください", tokens: ["def", "__str__(self):", "return self.name"], unit: "oop" },
    { prompt: "メソッドを属性のように扱うプロパティに並べ替えてください", tokens: ["@property", "def", "name(self):", "return self._name"], unit: "oop" },
    { prompt: "複数のクラスを継承するコードに並べ替えてください", tokens: ["class", "Duck(Swimmer, Flyer):", "pass"], unit: "oop" },
    { prompt: "インスタンスなしで呼べる静的メソッドに並べ替えてください", tokens: ["@staticmethod", "def", "add(a, b):", "return a + b"], unit: "oop" },
    { prompt: "クラス自体を引数に取るクラスメソッドに並べ替えてください", tokens: ["@classmethod", "def", "create(cls):", "return cls()"], unit: "oop" },
    { prompt: "犬のインスタンスを作ってメソッドを呼び出すコードに並べ替えてください", tokens: ["dog", "=", "Dog()", "dog.bark()"], unit: "oop" },
    { prompt: "同じ名前のメソッドを順番に呼び出すコードに並べ替えてください", tokens: ["for", "animal in animals:", "animal.speak()"], unit: "oop" },
    { prompt: "アンダースコアで始まる非公開の属性に並べ替えてください", tokens: ["self._name", "=", "name"], unit: "oop" },
    { prompt: "self.speedを更新するメソッドに並べ替えてください", tokens: ["def", "accelerate(self):", "self.speed += 10"], unit: "oop" },
    // 例外処理
    { prompt: "エラーを捕まえて表示するコードに並べ替えてください", tokens: ["try:", "risky()", "except Exception as e:", "print(e)"], unit: "error" },
    { prompt: "ファイルを安全に開くコードに並べ替えてください", tokens: ["with", "open(\"data.txt\") as f:", "content = f.read()"], unit: "error" },
    { prompt: "0で割ったときのエラーを捕まえるコードに並べ替えてください", tokens: ["try:", "1 / 0", "except ZeroDivisionError:", "print(\"NG\")"], unit: "error" },
    { prompt: "エラーの有無にかかわらず実行するコードに並べ替えてください", tokens: ["try:", "risky()", "finally:", "print(\"done\")"], unit: "error" },
    { prompt: "xが負の数ならエラーを発生させるコードに並べ替えてください", tokens: ["if", "x < 0:", "raise ValueError(\"negative\")"], unit: "error" },
    { prompt: "xが正の数であることを確認するコードに並べ替えてください", tokens: ["assert", "x > 0,", "\"xは正の数である必要があります\""], unit: "error" },
    { prompt: "複数の種類のエラーをまとめて捕まえるコードに並べ替えてください", tokens: ["except", "(ValueError, TypeError):", "print(\"入力エラー\")"], unit: "error" },
    { prompt: "値が不正なときのエラーを捕まえるコードに並べ替えてください", tokens: ["try:", "int(\"abc\")", "except ValueError:", "print(\"変換失敗\")"], unit: "error" },
    { prompt: "型が違うときのエラーを捕まえるコードに並べ替えてください", tokens: ["try:", "\"1\" + 1", "except TypeError:", "print(\"型エラー\")"], unit: "error" },
    { prompt: "存在しないキーのエラーを捕まえるコードに並べ替えてください", tokens: ["try:", "person[\"age\"]", "except KeyError:", "print(\"キーなし\")"], unit: "error" },
    { prompt: "範囲外のインデックスのエラーを捕まえるコードに並べ替えてください", tokens: ["try:", "numbers[10]", "except IndexError:", "print(\"範囲外\")"], unit: "error" },
    { prompt: "自分で定義したエラークラスに並べ替えてください", tokens: ["class", "MyError(Exception):", "pass"], unit: "error" },
    { prompt: "意図的にカスタム例外を発生させるコードに並べ替えてください", tokens: ["raise", "MyError(\"問題発生\")"], unit: "error" },
    { prompt: "捕まえたエラーをそのまま再び発生させるコードに並べ替えてください", tokens: ["except", "Exception as e:", "raise"], unit: "error" },
    { prompt: "デバッグのために変数の値を表示するコードに並べ替えてください", tokens: ["print(", "f\"x = {x}\"", ")"], unit: "error" },
    { prompt: "ログにメッセージを記録するコードに並べ替えてください", tokens: ["logging.info(", "\"処理を開始しました\"", ")"], unit: "error" },
    { prompt: "ファイルへの書き込みをwith文で行うコードに並べ替えてください", tokens: ["with", "open(\"log.txt\") as f:", "f.write(\"done\")"], unit: "error" },
    { prompt: "エラーの詳細をそのまま表示するコードに並べ替えてください", tokens: ["except", "Exception as e:", "print(e)"], unit: "error" },
    { prompt: "0で割ることを事前に防ぐコードに並べ替えてください", tokens: ["if", "b == 0:", "raise ValueError(\"0では割れません\")"], unit: "error" },
    { prompt: "エラーが起きてもプログラムを止めないコードに並べ替えてください", tokens: ["try:", "process()", "except Exception:", "pass"], unit: "error" },
    // 応用：関数から移動した高度な内容（再帰・高階関数・クロージャなど）
    { prompt: "自分自身を呼び出す再帰関数に並べ替えてください", tokens: ["def", "countdown(n):", "return countdown(n - 1)"], unit: "advanced" },
    { prompt: "関数の中でグローバル変数を書き換えるコードに並べ替えてください", tokens: ["def", "increment():", "global count", "count += 1"], unit: "advanced" },
    { prompt: "別の関数を引数として受け取る高階関数に並べ替えてください", tokens: ["def", "apply(func, x):", "return func(x)"], unit: "advanced" },
    { prompt: "関数を定義してすぐに呼び出すコードに並べ替えてください", tokens: ["result", "=", "(lambda x: x + 1)(5)"], unit: "advanced" },
    { prompt: "別の関数をそのまま返す関数に並べ替えてください", tokens: ["def", "wrapper(func):", "return func"], unit: "advanced" },
    { prompt: "関数アノテーションで型を指定するコードに並べ替えてください", tokens: ["def", "greet(name: str) -> str:", "return name"], unit: "advanced" },
    { prompt: "可変長引数をすべて合計する関数に並べ替えてください", tokens: ["def", "total(*nums):", "return sum(nums)"], unit: "advanced" },
    { prompt: "関数の外にある変数を参照するコードに並べ替えてください", tokens: ["message", "=", "\"Hi\"", "def", "show():", "print(message)"], unit: "advanced" },
    { prompt: "計算結果をキャッシュに保存するコードに並べ替えてください", tokens: ["cache[key]", "=", "result"], unit: "advanced" },
    { prompt: "再帰で階乗を求める関数に並べ替えてください", tokens: ["def", "factorial(n):", "return n * factorial(n - 1)"], unit: "advanced" },
    // 応用
    { prompt: "関数にデコレータを付けるコードに並べ替えてください", tokens: ["@log", "def", "greet():", "pass"], unit: "advanced" },
    { prompt: "ジェネレータ関数を定義するコードに並べ替えてください", tokens: ["def", "counter():", "yield 1"], unit: "advanced" },
    { prompt: "リスト内包表記で2倍のリストを作るコードに並べ替えてください", tokens: ["doubled", "=", "[n * 2 for n in numbers]"], unit: "advanced" },
    { prompt: "値を複数返すジェネレータに並べ替えてください", tokens: ["def", "counter():", "yield 1", "yield 2"], unit: "advanced" },
    { prompt: "直接実行されたときだけ動くコードに並べ替えてください", tokens: ["if", "__name__ == \"__main__\":", "main()"], unit: "advanced" },
    { prompt: "型ヒントを付けて関数を定義するコードに並べ替えてください", tokens: ["def", "add(a: int, b: int) -> int:", "return a + b"], unit: "advanced" },
    { prompt: "ジェネレータ式で2倍の値を作るコードに並べ替えてください", tokens: ["doubled", "=", "(n * 2 for n in numbers)"], unit: "advanced" },
    { prompt: "イテレータから値を1つずつ取り出すコードに並べ替えてください", tokens: ["it", "=", "iter(numbers)", "next(it)"], unit: "advanced" },
    { prompt: "標準ライブラリのmathを使うコードに並べ替えてください", tokens: ["import", "math", "math.sqrt(16)"], unit: "advanced" },
    { prompt: "特定の関数だけをインポートして使うコードに並べ替えてください", tokens: ["from", "math import sqrt", "sqrt(16)"], unit: "advanced" },
    { prompt: "標準ライブラリのdatetimeで今日の日付を取得するコードに並べ替えてください", tokens: ["import", "datetime", "datetime.date.today()"], unit: "advanced" },
    { prompt: "外部パッケージをインストールするコマンドに並べ替えてください", tokens: ["pip", "install", "requests"], unit: "advanced" },
    { prompt: "with文でファイルを安全に読み込むコードに並べ替えてください", tokens: ["with", "open(\"data.txt\") as f:", "data = f.read()"], unit: "advanced" },
    { prompt: "仮想環境を作成するコマンドに並べ替えてください", tokens: ["python", "-m", "venv env"], unit: "advanced" },
    { prompt: "スレッドを使って並行処理するコードに並べ替えてください", tokens: ["thread", "=", "threading.Thread(target=task)"], unit: "advanced" },
    { prompt: "プロセスを使って並行処理するコードに並べ替えてください", tokens: ["process", "=", "multiprocessing.Process(target=task)"], unit: "advanced" },
    { prompt: "実行中にメソッドを書き換えるモンキーパッチに並べ替えてください", tokens: ["Dog.bark", "=", "new_bark"], unit: "advanced" },
    { prompt: "メタクラスを指定してクラスを定義するコードに並べ替えてください", tokens: ["class", "Dog(metaclass=Meta):", "pass"], unit: "advanced" },
    { prompt: "PEP8に沿ってスネークケースで変数を定義するコードに並べ替えてください", tokens: ["user_name", "=", "\"Taro\""], unit: "advanced" },
    { prompt: "オブジェクトがイテラブルかどうかを確認するコードに並べ替えてください", tokens: ["from", "collections.abc import Iterable", "isinstance(numbers, Iterable)"], unit: "advanced" },
  ],
  html: [
    // 構造タグ
    { prompt: "文字を装飾するspanタグに並べ替えてください", tokens: ["<div>", "テキストの", "<span>一部</span>", "を強調</div>"], unit: "tag_basic" },
    { prompt: "2つの段落を並べるコードに並べ替えてください", tokens: ["<p>1つ目</p>", "<p>2つ目</p>"], unit: "tag_basic" },
    { prompt: "div要素の中にp要素を入れるコードに並べ替えてください", tokens: ["<div>", "<p>内容</p>", "</div>"], unit: "tag_basic" },
    // 見出し・段落
    { prompt: "見出しと段落を作るコードに並べ替えてください", tokens: ["<h1>タイトル</h1>", "<p>本文です</p>"], unit: "heading_text" },
    { prompt: "2段階の見出しを作るコードに並べ替えてください", tokens: ["<h1>大見出し</h1>", "<h2>小見出し</h2>"], unit: "heading_text" },
    { prompt: "文章の一部を強調するコードに並べ替えてください", tokens: ["<p>", "<strong>重要</strong>", "です</p>"], unit: "heading_text" },
    // リンク・画像
    { prompt: "リンクを作るコードに並べ替えてください", tokens: ["<a href=\"https://example.com\">", "リンク", "</a>"], unit: "link_media" },
    { prompt: "画像を表示するコードに並べ替えてください", tokens: ["<img", "src=\"cat.png\"", "alt=\"猫\">"], unit: "link_media" },
    { prompt: "新しいタブで開くリンクを作るコードに並べ替えてください", tokens: ["<a href=\"page.html\"", "target=\"_blank\">", "リンク</a>"], unit: "link_media" },
    // リスト・表
    { prompt: "箇条書きリストを作るコードに並べ替えてください", tokens: ["<ul>", "<li>りんご</li>", "<li>バナナ</li>", "</ul>"], unit: "list_table" },
    { prompt: "番号付きリストを作るコードに並べ替えてください", tokens: ["<ol>", "<li>1番目</li>", "<li>2番目</li>", "</ol>"], unit: "list_table" },
    { prompt: "見出し行のある表を作るコードに並べ替えてください", tokens: ["<table>", "<tr><th>名前</th></tr>", "</table>"], unit: "list_table" },
    // フォーム
    { prompt: "入力欄のあるフォームを作るコードに並べ替えてください", tokens: ["<form>", "<input type=\"text\">", "</form>"], unit: "form" },
    { prompt: "送信ボタンを持つフォームを作るコードに並べ替えてください", tokens: ["<form>", "<button type=\"submit\">", "送信</button></form>"], unit: "form" },
    { prompt: "選択肢のあるセレクトボックスを作るコードに並べ替えてください", tokens: ["<select>", "<option>りんご</option>", "</select>"], unit: "form" },
    // 属性
    { prompt: "id属性を持つdivを作るコードに並べ替えてください", tokens: ["<div", "id=\"main\">", "内容", "</div>"], unit: "attr" },
    { prompt: "複数のclassを指定するコードに並べ替えてください", tokens: ["<div", "class=\"card active\">", "内容</div>"], unit: "attr" },
    { prompt: "リンク先を新しいウィンドウで開かないよう指定するコードに並べ替えてください", tokens: ["<a", "href=\"page.html\"", "rel=\"noopener\">", "リンク</a>"], unit: "attr" },
    // データ・アクセシビリティ
    { prompt: "data属性を持つ要素を作るコードに並べ替えてください", tokens: ["<li", "data-id=\"3\">", "商品", "</li>"], unit: "data_a11y" },
    { prompt: "画像に代替テキストを付けるコードに並べ替えてください", tokens: ["<img", "src=\"logo.png\"", "alt=\"会社ロゴ\">"], unit: "data_a11y" },
    { prompt: "ボタンにaria-labelを付けるコードに並べ替えてください", tokens: ["<button", "aria-label=\"閉じる\">", "×</button>"], unit: "data_a11y" },
    // セマンティック・応用
    { prompt: "画像を囲むセクションを作るコードに並べ替えてください", tokens: ["<section>", "<img src=\"photo.png\">", "</section>"], unit: "semantic" },
    { prompt: "ページのフッターを作るコードに並べ替えてください", tokens: ["<footer>", "<p>&copy; 2026</p>", "</footer>"], unit: "semantic" },
    { prompt: "ナビゲーションを作るコードに並べ替えてください", tokens: ["<nav>", "<a href=\"/\">ホーム</a>", "</nav>"], unit: "semantic" },
  ],
  css: [
    // 文字
    { prompt: "見出しの文字色を青にするコードに並べ替えてください", tokens: ["h1", "{", "color: blue;", "}"], unit: "text" },
    { prompt: "文字を太字にするコードに並べ替えてください", tokens: ["p", "{", "font-weight: bold;", "}"], unit: "text" },
    { prompt: "文字を中央揃えにするコードに並べ替えてください", tokens: [".title", "{", "text-align: center;", "}"], unit: "text" },
    // 背景
    { prompt: "背景を薄いグレーにするコードに並べ替えてください", tokens: ["body", "{", "background-color: #eee;", "}"], unit: "background" },
    { prompt: "背景に画像を設定するコードに並べ替えてください", tokens: [".hero", "{", "background-image: url(\"bg.png\");", "}"], unit: "background" },
    { prompt: "背景色を半透明にするコードに並べ替えてください", tokens: [".overlay", "{", "background-color: rgba(0,0,0,0.5);", "}"], unit: "background" },
    // 余白・枠線
    { prompt: "ボックスに内側の余白をつけるコードに並べ替えてください", tokens: [".box", "{", "padding: 20px;", "}"], unit: "box" },
    { prompt: "カードに枠線をつけるコードに並べ替えてください", tokens: [".card", "{", "border: 1px solid #ccc;", "}"], unit: "box" },
    { prompt: "ボタンの角を丸くするコードに並べ替えてください", tokens: [".button", "{", "border-radius: 8px;", "}"], unit: "box" },
    // セレクタ・状態
    { prompt: "ホバー時に文字色を変えるコードに並べ替えてください", tokens: ["a:hover", "{", "color: red;", "}"], unit: "selector" },
    { prompt: "最初の子要素だけ色を変えるコードに並べ替えてください", tokens: ["li:first-child", "{", "color: green;", "}"], unit: "selector" },
    { prompt: "2つのクラスを持つ要素を選ぶコードに並べ替えてください", tokens: [".card.active", "{", "border-color: blue;", "}"], unit: "selector" },
    // フレックス・グリッド
    { prompt: "要素を横並びにするコードに並べ替えてください", tokens: [".container", "{", "display: flex;", "}"], unit: "layout" },
    { prompt: "要素をグリッドで並べるコードに並べ替えてください", tokens: [".grid", "{", "display: grid;", "}"], unit: "layout" },
    { prompt: "要素を画面の中央に配置するコードに並べ替えてください", tokens: [".box", "{", "margin: 0 auto;", "}"], unit: "layout" },
    // 配置
    { prompt: "要素を右上に固定するコードに並べ替えてください", tokens: [".badge", "{", "position: absolute;", "}"], unit: "position" },
    { prompt: "要素を画面上部に固定するコードに並べ替えてください", tokens: [".header", "{", "position: fixed;", "}"], unit: "position" },
    { prompt: "重なり順を最前面にするコードに並べ替えてください", tokens: [".modal", "{", "z-index: 999;", "}"], unit: "position" },
    // アニメーション
    { prompt: "ホバー時の色の変化をなめらかにするコードに並べ替えてください", tokens: ["button", "{", "transition: color 0.3s;", "}"], unit: "animation" },
    { prompt: "要素を回転させるコードに並べ替えてください", tokens: [".icon", "{", "transform: rotate(45deg);", "}"], unit: "animation" },
    { prompt: "点滅するアニメーションを定義するコードに並べ替えてください", tokens: ["@keyframes blink", "{", "50% { opacity: 0; }", "}"], unit: "animation" },
    // レスポンシブ・計算
    { prompt: "画面幅600px以下で文字を小さくするコードに並べ替えてください", tokens: ["@media (max-width: 600px)", "{", "p { font-size: 14px; }", "}"], unit: "responsive" },
    { prompt: "画像の幅を画面いっぱいに可変にするコードに並べ替えてください", tokens: ["img", "{", "width: 100%;", "}"], unit: "responsive" },
    { prompt: "余白を画面幅に応じて指定するコードに並べ替えてください", tokens: [".box", "{", "padding: 5vw;", "}"], unit: "responsive" },
  ],
  javascript: [
    // 出力・変数
    { prompt: "変数xに5を代入するコードに並べ替えてください", tokens: ["let", "x", "=", "5;"], unit: "output_var" },
    { prompt: "コンソールに「Hello」と表示するコードに並べ替えてください", tokens: ["console.log(", "\"Hello\"", ");"], unit: "output_var" },
    { prompt: "文字列を連結して表示するコードに並べ替えてください", tokens: ["console.log(", "\"Hi, \" + name", ");"], unit: "output_var" },
    // 関数の基本
    { prompt: "関数greetを定義するコードに並べ替えてください", tokens: ["function", "greet() {", "return \"Hello\";", "}"], unit: "func_basic" },
    { prompt: "2つの数を足す関数を定義するコードに並べ替えてください", tokens: ["function", "add(a, b) {", "return a + b;", "}"], unit: "func_basic" },
    { prompt: "何も返さない関数を定義するコードに並べ替えてください", tokens: ["function", "sayHi() {", "console.log(\"Hi\");", "}"], unit: "func_basic" },
    // 制御構文
    { prompt: "xが1なら「Yes」と表示するコードに並べ替えてください", tokens: ["if", "(x === 1) {", "console.log(\"Yes\");", "}"], unit: "control" },
    { prompt: "1から3まで繰り返すfor文に並べ替えてください", tokens: ["for", "(let i = 1; i <= 3; i++) {", "console.log(i);", "}"], unit: "control" },
    { prompt: "xが5未満の間繰り返すwhile文に並べ替えてください", tokens: ["while", "(x < 5) {", "x++;", "}"], unit: "control" },
    // 配列・データ
    { prompt: "配列numbersを作成するコードに並べ替えてください", tokens: ["const", "numbers", "=", "[1, 2, 3];"], unit: "data" },
    { prompt: "オブジェクトuserを作成するコードに並べ替えてください", tokens: ["const", "user", "=", "{ name: \"Taro\" };"] , unit: "data" },
    { prompt: "JSON文字列をオブジェクトに変換するコードに並べ替えてください", tokens: ["const", "data", "=", "JSON.parse(text);"], unit: "data" },
    // DOM・イベント
    { prompt: "ボタンにクリックイベントを登録するコードに並べ替えてください", tokens: ["button.addEventListener(", "\"click\",", "() => {}", ");"], unit: "dom" },
    { prompt: "idを指定して要素を取得するコードに並べ替えてください", tokens: ["const", "el", "=", "document.getElementById(\"box\");"], unit: "dom" },
    { prompt: "要素のテキストを書き換えるコードに並べ替えてください", tokens: ["el.textContent", "=", "\"更新しました\";"], unit: "dom" },
    // 関数の書き方
    { prompt: "配列の各要素を2倍にするコードに並べ替えてください", tokens: ["numbers.map(", "n => n * 2", ");"], unit: "func_style" },
    { prompt: "配列から条件に合う要素だけ残すコードに並べ替えてください", tokens: ["numbers.filter(", "n => n > 0", ");"], unit: "func_style" },
    { prompt: "アロー関数で2倍にする関数を定義するコードに並べ替えてください", tokens: ["const", "double", "=", "n => n * 2;"], unit: "func_style" },
    // 非同期処理
    { prompt: "非同期でデータを取得するコードに並べ替えてください", tokens: ["async function", "load() {", "await fetch(url);", "}"], unit: "async" },
    { prompt: "1秒後に実行するコードに並べ替えてください", tokens: ["setTimeout(", "() => console.log(\"done\")", ", 1000);"], unit: "async" },
    { prompt: "非同期処理の失敗を捕まえるコードに並べ替えてください", tokens: ["fetch(url)", ".catch(", "err => console.log(err)", ")"], unit: "async" },
    // スコープ・応用
    { prompt: "クロージャで数を数えるコードに並べ替えてください", tokens: ["function counter() {", "let n = 0;", "return () => n++;", "}"], unit: "scope" },
    { prompt: "配列の中身をコピーするスプレッド構文に並べ替えてください", tokens: ["const", "copy", "=", "[...numbers];"], unit: "scope" },
    { prompt: "オブジェクトのメソッドの中でthisを使うコードに並べ替えてください", tokens: ["const", "obj", "=", "{ greet() { return this.name; } };"], unit: "scope" },
  ],
};
